// Generated by build_contracts.py. Do not edit directly.
enum BrowserReadBudget {
    static let maxNodes = 1...65536
    static let maxDepth = 1...256
    static let maxBytes = 8192...33554432
    static let maxCaptureMs = 100...20000
    static let maxCaptures = 1...100
    static let deadlineMs = 1000...600000
}
