// Generated by build_contracts.py. Do not edit directly.
export const readLimitRanges = Object.freeze({
  "maxNodes": [
    1,
    65536
  ],
  "maxDepth": [
    1,
    256
  ],
  "maxBytes": [
    8192,
    33554432
  ],
  "maxCaptureMs": [
    100,
    20000
  ],
  "maxCaptures": [
    1,
    100
  ],
  "deadlineMs": [
    1000,
    600000
  ]
} as const);
export const defaultReadLimits = Object.freeze({
  "maxNodes": 32768,
  "maxDepth": 128,
  "maxBytes": 16777216,
  "maxCaptureMs": 10000,
  "maxCaptures": 10,
  "deadlineMs": 60000
} as const);
export const projectionLimitRanges = Object.freeze({
  "maxRecords": [
    1,
    65536
  ],
  "maxOutputBytes": [
    8192,
    134217728
  ]
} as const);
export const defaultProjectionLimits = Object.freeze({
  "maxRecords": 32768,
  "maxOutputBytes": 67108864
} as const);
